import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Legal - KOTOMO',
  description: 'Privacy Policy and Terms of Service for KOTOMO AI Podcast Generator',
};

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-[#050507] text-[#ededed]">
      <nav className="border-b border-white/5 bg-[#050507]/80 backdrop-blur-md">
        <div className="max-w-3xl mx-auto px-6 h-16 flex items-center">
          <Link
            href="/"
            className="flex items-center gap-2 text-sm font-medium text-[#a1a1aa] hover:text-white transition-colors"
          >
            <span className="text-[#06b6d4]">←</span> Back to KOTOMO
          </Link>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-6 py-12 space-y-16">
        <header>
          <h1 className="text-2xl font-semibold text-white tracking-tight">Legal</h1>
          <p className="text-sm text-[#a1a1aa] mt-1">Privacy Policy and Terms of Service</p>
        </header>

        <section className="linear-card rounded-xl p-8 space-y-6">
          <h2 className="text-lg font-semibold text-white">Privacy Policy</h2>
          <p className="text-xs text-[#a1a1aa]">Last updated: February 2025</p>

          <div className="space-y-4 text-sm text-[#a1a1aa] leading-relaxed">
            <div>
              <h3 className="text-white font-medium mb-2">Information We Collect</h3>
              <p>
                When you use KOTOMO, we process the topics you enter to generate podcast episodes.
                We do not collect account or personal identification unless you sign in through a
                third-party provider. Audio is generated via AI and may be temporarily processed on
                our infrastructure.
              </p>
            </div>
            <div>
              <h3 className="text-white font-medium mb-2">Storage</h3>
              <p>
                When storage is enabled, generated audio may be uploaded to Vercel Blob storage to
                provide you with a persistent playback URL. We do not use your data for training
                models or advertising.
              </p>
            </div>
            <div>
              <h3 className="text-white font-medium mb-2">Sale of Data</h3>
              <p>
                We do not sell your personal data or topic inputs to third parties.
              </p>
            </div>
            <div>
              <h3 className="text-white font-medium mb-2">Cookies and Tracking</h3>
              <p>
                We use minimal cookies and similar technologies only as needed to operate the
                service (e.g. session state). We do not use third-party advertising or tracking
                cookies.
              </p>
            </div>
            <div>
              <h3 className="text-white font-medium mb-2">Contact</h3>
              <p>
                For privacy-related questions, contact us via the links in the footer (e.g. GitHub,
                Twitter) or your preferred channel listed on the KOTOMO site.
              </p>
            </div>
          </div>
        </section>

        <section className="linear-card rounded-xl p-8 space-y-6">
          <h2 className="text-lg font-semibold text-white">Terms of Service</h2>
          <p className="text-xs text-[#a1a1aa]">Last updated: February 2025</p>

          <div className="space-y-4 text-sm text-[#a1a1aa] leading-relaxed">
            <div>
              <h3 className="text-white font-medium mb-2">Acceptable Use</h3>
              <p>
                You may use KOTOMO only for lawful purposes. You must not use the service to
                generate content that is illegal, harmful, infringing, or that violates the rights
                of others. We reserve the right to suspend or terminate access for misuse.
              </p>
            </div>
            <div>
              <h3 className="text-white font-medium mb-2">AI-Generated Content</h3>
              <p>
                Episodes are generated by AI. We do not guarantee accuracy, completeness, or
                suitability for any purpose. You are responsible for how you use the generated
                content and for verifying any facts or claims before relying on them.
              </p>
            </div>
            <div>
              <h3 className="text-white font-medium mb-2">Intellectual Property</h3>
              <p>
                You retain ownership of the topics you submit. Subject to these terms, you own the
                audio output generated for you. KOTOMO and its branding remain our property.
              </p>
            </div>
            <div>
              <h3 className="text-white font-medium mb-2">Service Availability</h3>
              <p>
                We strive for reliability but do not guarantee uninterrupted service. The service
                is provided &quot;as is&quot; and we may change or discontinue features with
                reasonable notice where practicable.
              </p>
            </div>
            <div>
              <h3 className="text-white font-medium mb-2">Limitation of Liability</h3>
              <p>
                To the fullest extent permitted by law, KOTOMO and its operators shall not be
                liable for any indirect, incidental, special, or consequential damages arising from
                your use of the service. Our total liability is limited to the amount you paid to
                use the service in the twelve months preceding the claim, or zero if the service
                was free.
              </p>
            </div>
          </div>
        </section>

        <div className="pt-4">
          <Link
            href="/"
            className="text-sm font-medium text-[#06b6d4] hover:underline"
          >
            ← Return home
          </Link>
        </div>
      </main>
    </div>
  );
}
